using System;
using System.IO;
using E2EApi.Persistence;
using HarmonyLib;

namespace E2EApi.Features
{
    /// <summary>
    /// Steam Workshop interoperability for mod-required maps.
    ///
    /// The Workshop upload pipeline is already handled by
    /// <see cref="VanillaFallback"/> (which stages the Level.e2e sidecar into
    /// the UGC content folder before the upload fires). This class extends that
    /// with two additional behaviours:
    ///
    /// 1. <b>Upload enrichment</b>: when a map is flagged
    ///    <c>RequiresMod = true</c>, a lightweight companion file
    ///    <c>e2e_workshop_meta.txt</c> is written alongside the UGC content.
    ///    It carries the mod version requirement and a human-readable notice.
    ///    Vanilla clients never read this file; mod clients pick it up on
    ///    download to verify compatibility.
    ///
    /// 2. <b>Download-side compatibility check</b>: when a Workshop map is
    ///    resolved for play (via <see cref="VanillaFallback"/>'s
    ///    <c>GetCustomLevelFilePath</c> postfix), this class reads
    ///    <c>e2e_workshop_meta.txt</c> (if present) and fires
    ///    <see cref="WorkshopMapLoaded"/> with the metadata so the UI can show
    ///    a "this map was made with E2E Map Editor vX.Y.Z" banner.
    ///
    /// Both behaviours are passive: they never block saves/loads and fail
    /// silently on any I/O or reflection error.
    /// </summary>
    public static class WorkshopInterop
    {
        /// <summary>Name of the companion metadata file placed in the UGC folder.</summary>
        public const string MetaFileName = "e2e_workshop_meta.txt";

        /// <summary>
        /// Fired on the main thread when a Workshop map that carries
        /// <see cref="MetaFileName"/> is resolved for play.
        /// </summary>
        public static event Action<WorkshopMapMeta> WorkshopMapLoaded;

        private static bool _initialised;

        public static void Initialise()
        {
            if (_initialised) return;
            _initialised = true;
            PatchRegistry.EnsurePatched(typeof(WorkshopPatches));
        }

        // ── metadata model ────────────────────────────────────────────────────

        public class WorkshopMapMeta
        {
            /// <summary>Mod version the map was built with.</summary>
            public string ModVersion;
            /// <summary>True when the map requires the mod to play correctly.</summary>
            public bool RequiresMod;
            /// <summary>Full path to the map's folder.</summary>
            public string MapDirectory;

            /// <summary>Human-readable compatibility description.</summary>
            public string CompatibilityNote =>
                RequiresMod
                    ? $"This map requires E2E Map Editor v{ModVersion} or later."
                    : $"This map was created with E2E Map Editor v{ModVersion}.";
        }

        // ── serialization ─────────────────────────────────────────────────────

        private static string Serialize(WorkshopMapMeta meta)
        {
            return "e2e_version=" + (meta.ModVersion ?? "") + "\n" +
                   "requires_mod=" + (meta.RequiresMod ? "true" : "false") + "\n" +
                   "# This file is generated by the E2E Map Editor mod.\n" +
                   "# It is used to identify modded Workshop maps.\n" +
                   "# Vanilla clients ignore it.\n";
        }

        private static WorkshopMapMeta Deserialize(string text, string mapDir)
        {
            var meta = new WorkshopMapMeta { MapDirectory = mapDir };
            if (string.IsNullOrEmpty(text)) return meta;
            foreach (var line in text.Replace("\r\n", "\n").Split('\n'))
            {
                if (line.StartsWith("e2e_version="))
                    meta.ModVersion = line.Substring("e2e_version=".Length).Trim();
                else if (line.StartsWith("requires_mod="))
                    meta.RequiresMod = line.Substring("requires_mod=".Length).Trim() == "true";
            }
            return meta;
        }

        // ── upload helper ─────────────────────────────────────────────────────

        /// <summary>
        /// Write or remove <see cref="MetaFileName"/> in <paramref name="ugcContentPath"/>
        /// based on whether the current sidecar has <c>RequiresMod</c> set.
        /// Called from the Workshop upload prefix patch.
        /// </summary>
        internal static void StageMetaFile(string ugcContentPath)
        {
            if (string.IsNullOrEmpty(ugcContentPath) || !Directory.Exists(ugcContentPath))
                return;

            string metaPath = Path.Combine(ugcContentPath, MetaFileName);
            var extras = ModExtras.Current;

            // Only write the meta file when there is actual mod content or the
            // map explicitly flags itself as requiring the mod.
            bool hasContent = extras.RequiresMod
                || extras.Section("fences").Count > 0
                || extras.Section("triggers").Count > 0
                || extras.Section("tiles").Count > 0
                || extras.Section("customAssets").Count > 0;

            if (!hasContent)
            {
                if (File.Exists(metaPath))
                    File.Delete(metaPath);
                return;
            }

            var meta = new WorkshopMapMeta
            {
                ModVersion = E2EApiInfo.Version,
                RequiresMod = extras.RequiresMod,
            };
            File.WriteAllText(metaPath, Serialize(meta));
            Log.Info("WorkshopInterop: staged " + MetaFileName + " for Workshop upload");
        }

        // ── download helper ───────────────────────────────────────────────────

        /// <summary>
        /// Check <paramref name="mapDirectory"/> for a meta file and fire
        /// <see cref="WorkshopMapLoaded"/> when one is found.
        /// Called from the GetCustomLevelFilePath postfix patch.
        /// </summary>
        internal static void CheckDownloadedMap(string mapDirectory)
        {
            if (string.IsNullOrEmpty(mapDirectory)) return;
            string metaPath = Path.Combine(mapDirectory, MetaFileName);
            if (!File.Exists(metaPath)) return;

            try
            {
                string text = File.ReadAllText(metaPath);
                var meta = Deserialize(text, mapDirectory);
                Log.Info("WorkshopInterop: Workshop map requires E2E v" + meta.ModVersion);
                var handler = WorkshopMapLoaded;
                if (handler != null) handler(meta);
            }
            catch (Exception e)
            {
                Log.Warn("WorkshopInterop: failed to read meta file: " + e.Message);
            }
        }

        // ── patches ───────────────────────────────────────────────────────────

        [HarmonyPatch]
        private static class WorkshopPatches
        {
            /// <summary>
            /// Extend the existing VanillaFallback upload prefix: also write
            /// the Workshop meta file alongside the sidecar.
            /// </summary>
            [HarmonyPatch(typeof(SteamPlatform), nameof(SteamPlatform.UploadUGCItem))]
            [HarmonyPrefix]
            private static void BeforeUploadUGCItem(Platform.UGCUploadData uploadData)
            {
                try
                {
                    if (uploadData == null ||
                        uploadData.m_ugcType != Platform.UGCType.eCustomLevel ||
                        string.IsNullOrEmpty(uploadData.m_strContentPath) ||
                        !Directory.Exists(uploadData.m_strContentPath))
                        return;

                    StageMetaFile(uploadData.m_strContentPath);
                }
                catch (Exception e)
                {
                    Log.Error("WorkshopInterop upload hook failed: " + e);
                }
            }

            /// <summary>
            /// After the game resolves a custom level file path, inspect the
            /// directory for a Workshop meta file and notify subscribers.
            /// </summary>
            [HarmonyPatch(typeof(SaveManager), nameof(SaveManager.GetCustomLevelFilePath))]
            [HarmonyPostfix]
            private static void AfterGetCustomLevelFilePath(ref string __result)
            {
                if (string.IsNullOrEmpty(__result)) return;
                try
                {
                    CheckDownloadedMap(Path.GetDirectoryName(__result));
                }
                catch (Exception e)
                {
                    Log.Error("WorkshopInterop download hook failed: " + e);
                }
            }
        }
    }
}
