using System;
using System.Collections.Generic;
using UnityEngine;

public class CustomisationData : MonoBehaviour
{
	[Serializable]
	public class BodyData
	{
		[Serializable]
		public class OutfitData
		{
			public Outfit outfit = Outfit.COUNT;

			public Material material;
		}

		public BodyType bodyType = BodyType.COUNT;

		public SkinColour skinColour = SkinColour.COUNT;

		public List<OutfitData> outfitData = new List<OutfitData>();

		public Material GetMaterialForOutfit(Outfit outfit)
		{
			Material material = null;
			if (outfit >= Outfit.NONE && (int)outfit < outfitData.Count)
			{
				material = outfitData[(int)outfit].material;
			}
			if (material == null)
			{
			}
			return material;
		}
	}

	[Serializable]
	public class HairData
	{
		public Hair hair = Hair.COUNT;

		public Material material;
	}

	[Serializable]
	public class HatData
	{
		public Hat hat = Hat.COUNT;

		public Material material;
	}

	[Serializable]
	public class UpperFaceAccessoryData
	{
		public UpperFaceAccessory accessory = UpperFaceAccessory.COUNT;

		public Material material;
	}

	[Serializable]
	public class LowerFaceAccessoryData
	{
		public LowerFaceAccessory accessory = LowerFaceAccessory.COUNT;

		public Material material;
	}

	public enum BodyType
	{
		NULL = -1,
		FEMALE,
		MALE,
		COUNT
	}

	public enum SkinColour
	{
		NULL = -1,
		WHITE,
		BLACK,
		BLUE,
		BROWN,
		GREEN,
		GREY,
		ORANGE,
		PURPLE,
		RED,
		YELLOW,
		COUNT
	}

	public enum Outfit
	{
		NULL = -1,
		NONE,
		GUARD_01,
		INMATE_01,
		RIOTGUARD_01,
		MAINTENANCE_01,
		MAINTENANCE_02,
		MEDIC_01,
		WARDEN_01,
		JOBOFFICER_01,
		JOBOFFICER_02,
		ADMIRAL_01,
		CHEF_01,
		PILOT_01,
		TRAINDRIVER_01,
		ANCHORMAN_01,
		BOILER_01,
		CAMERAOPERATOR_01,
		COWGIRL_01,
		DICTATOR_01,
		DIRTYJANITOR_01,
		GUARD_SHORTSLEEVES_01,
		GULAGGUARD_01,
		INFIRMARY_01,
		INMATE_STRIPY_01,
		INMATE_STRIPYSHORT_01,
		MIB_01,
		MILITARYGUARD_01,
		SPACESUIT_01,
		RUSSIANPEASANT_01,
		SCIENTIST_01,
		SHERIFF_01,
		INMATE_DIRTY_01,
		INMATE_GREY_01,
		INMATE_YELLOW_01,
		ROBOTGUARD_01,
		FAKEROBOTGUARD_01,
		DLC02_MEDIC,
		DLC02_GUARD,
		DLC02_MAINTENANCE,
		DLC02_CHEF,
		DLC02_GRIMREAPER,
		DLC02_ZOMBIE1,
		DLC02_ZOMBIE2,
		DLC02_ZOMBIE3,
		DLC02_ZOMBIE4,
		DLC02_INMATEPATIENT,
		DLC02_MADSCIENTIST,
		DLC03_SANTA_01,
		INMATECLOWN_01,
		INMATECLOWN_02,
		MAGICIAN01,
		RINGMASTER01,
		STRONGMAN01,
		DLC04_CASUAL_01,
		DLC04_CASUAL_02,
		DLC04_CASUAL_03,
		DLC04_CASUAL_04,
		DLC04_CASUAL_05,
		DLC04_CASUAL_06,
		DLC04_CASUAL_07,
		DLC04_CASUAL_08,
		DLC04_CASUAL_09,
		DLC04_CASUAL_10,
		DLC04_CASUAL_11,
		DLC04_CASUAL_12,
		DLC04_CASUAL_13,
		DLC04_CASUAL_14,
		DLC04_CASUAL_15,
		DLC04_CASUAL_16,
		ARMOR_01,
		MEDIEVALGUARD_01,
		PEASANT_01,
		DLC06_GUARDELF_01,
		DLC06_ELF_01,
		COUNT
	}

	public enum Hair
	{
		NULL = -1,
		NONE,
		DEBBIE_BLUE,
		DEBBIE_BROWN,
		DEBBIE_GREEN,
		DEBBIE_GREY,
		DEBBIE_ORANGE,
		DEBBIE_PURPLE,
		DEBBIE_RED,
		DEBBIE_WHITE,
		DEBBIE_YELLOW,
		BALDINGMALE_BLUE,
		BALDINGMALE_BROWN,
		BALDINGMALE_GREEN,
		BALDINGMALE_GREY,
		BALDINGMALE_ORANGE,
		BALDINGMALE_PURPLE,
		BALDINGMALE_RED,
		BALDINGMALE_WHITE,
		BALDINGMALE_YELLOW,
		BIGBOBFEMALE_BLUE,
		BIGBOBFEMALE_BROWN,
		BIGBOBFEMALE_GREEN,
		BIGBOBFEMALE_GREY,
		BIGBOBFEMALE_ORANGE,
		BIGBOBFEMALE_PURPLE,
		BIGBOBFEMALE_RED,
		BIGBOBFEMALE_WHITE,
		BIGBOBFEMALE_YELLOW,
		BOBFEMALE_BLUE,
		BOBFEMALE_BROWN,
		BOBFEMALE_GREEN,
		BOBFEMALE_GREY,
		BOBFEMALE_ORANGE,
		BOBFEMALE_PURPLE,
		BOBFEMALE_RED,
		BOBFEMALE_WHITE,
		BOBFEMALE_YELLOW,
		BUNFEMALE_BLUE,
		BUNFEMALE_BROWN,
		BUNFEMALE_GREEN,
		BUNFEMALE_GREY,
		BUNFEMALE_ORANGE,
		BUNFEMALE_PURPLE,
		BUNFEMALE_RED,
		BUNFEMALE_WHITE,
		BUNFEMALE_YELLOW,
		COMBEDMALE_BLUE,
		COMBEDMALE_BROWN,
		COMBEDMALE_GREEN,
		COMBEDMALE_GREY,
		COMBEDMALE_ORANGE,
		COMBEDMALE_PURPLE,
		COMBEDMALE_RED,
		COMBEDMALE_WHITE,
		COMBEDMALE_YELLOW,
		CURLYFEMALE_BLUE,
		CURLYFEMALE_BROWN,
		CURLYFEMALE_GREEN,
		CURLYFEMALE_GREY,
		CURLYFEMALE_ORANGE,
		CURLYFEMALE_PURPLE,
		CURLYFEMALE_RED,
		CURLYFEMALE_WHITE,
		CURLYFEMALE_YELLOW,
		FLATTOPMALE_BLUE,
		FLATTOPMALE_BROWN,
		FLATTOPMALE_GREEN,
		FLATTOPMALE_GREY,
		FLATTOPMALE_ORANGE,
		FLATTOPMALE_PURPLE,
		FLATTOPMALE_RED,
		FLATTOPMALE_WHITE,
		FLATTOPMALE_YELLOW,
		HAIRBANDFEMALE_BLUE,
		HAIRBANDFEMALE_BROWN,
		HAIRBANDFEMALE_GREEN,
		HAIRBANDFEMALE_GREY,
		HAIRBANDFEMALE_ORANGE,
		HAIRBANDFEMALE_PUPRLE,
		HAIRBANDFEMALE_RED,
		HAIRBANDFEMALE_WHITE,
		HAIRBANDFEMALE_YELLOW,
		HAIRGEL_MALE_BLUE,
		HAIRGEL_MALE_BROWN,
		HAIRGEL_MALE_GREY,
		HAIRGEL_MALE_ORANGE,
		HAIRGEL_MALE_PURPLE,
		HAIRGEL_MALE_RED,
		HAIRGEL_MALE_YELLOW,
		HOCKEYCUTMALE_BLUE,
		HOCKEYCUTMALE_BROWN,
		HOCKEYCUTMALE_GREEN,
		HOCKEYCUTMALE_GREY,
		HOCKEYCUTMALE_ORANGE,
		HOCKEYCUTMALE_PURPLE,
		HOCKEYCUTMALE_RED,
		HOCKEYCUTMALE_WHITE,
		HOCKEYCUTMALE_YELLOW,
		LONGLAYERSFEMALE_BLUE,
		LONGLAYERSFEMALE_BROWN,
		LONGLAYERSFEMALE_GREEN,
		LONGLAYERSFEMALE_GREY,
		LONGLAYERSFEMALE_ORANGE,
		LONGLAYERSFEMALE_PURPLE,
		LONGLAYERSFEMALE_RED,
		LONGLAYERSFEMALE_WHITE,
		LONGLAYERSFEMALE_YELLOW,
		MESSYMALE_BLUE,
		MESSYMALE_BROWN,
		MESSYMALE_GREEN,
		MESSYMALE_GREY,
		MESSYMALE_ORANGE,
		MESSYMALE_PURPLE,
		MESSYMALE_RED,
		MESSYMALE_WHITE,
		MESSYMALE_YELLOW,
		MESSYSIDEMALE_BLUE,
		MESSYSIDEMALE_BROWN,
		MESSYSIDEMALE_GREEN,
		MESSYSIDEMALE_GREY,
		MESSYSIDEMALE_ORANGE,
		MESSYSIDEMALE_PURPLE,
		MESSYSIDEMALE_RED,
		MESSYSIDEMALE_WHITE,
		MESSYSIDEMALE_YELLOW,
		MOHAWKMALE_BLUE,
		MOHAWKMALE_BROWN,
		MOHAWKMALE_GREEN,
		MOHAWKMALE_GREY,
		MOHAWKMALE_ORANGE,
		MOHAWKMALE_PURPLE,
		MOHAWKMALE_RED,
		MOHAWKMALE_WHITE,
		MOHAWKMALE_YELLOW,
		PARTEDMALE_BLUE,
		PARTEDMALE_BROWN,
		PARTEDMALE_GREEN,
		PARTEDMALE_GREY,
		PARTEDMALE_ORANGE,
		PARTEDMALE_PURPLE,
		PARTEDMALE_RED,
		PARTEDMALE_WHITE,
		PARTEDMALE_YELLOW,
		POMPADOURMALE_BLUE,
		POMPADOURMALE_BROWN,
		POMPADOURMALE_GREEN,
		POMPADOURMALE_GREY,
		POMPADOURMALE_ORANGE,
		POMPADOURMALE_PURPLE,
		POMPADOURMALE_RED,
		POMPADOURMALE_WHITE,
		POMPADOURMALE_YELLOW,
		PONYTAILFEMALE_BLUE,
		PONYTAILFEMALE_BROWN,
		PONYTAILFEMALE_GREEN,
		PONYTAILFEMALE_GREY,
		PONYTAILFEMALE_ORANGE,
		PONYTAILFEMALE_PURPLE,
		PONYTAILFEMALE_RED,
		PONYTAILFEMALE_WHITE,
		PONYTAILFEMALE_YELLOW,
		PONYTAILMALE_BLUE,
		PONYTAILMALE_BROWN,
		PONYTAILMALE_GREEN,
		PONYTAILMALE_GREY,
		PONYTAILMALE_ORANGE,
		PONYTAILMALE_PURPLE,
		PONYTAILMALE_RED,
		PONYTAILMALE_WHITE,
		PONYTAILMALE_YELLOW,
		SHORTFEMALE_BLUE,
		SHORTFEMALE_BROWN,
		SHORTFEMALE_GREEN,
		SHORTFEMALE_GREY,
		SHORTFEMALE_ORANGE,
		SHORTFEMALE_PURPLE,
		SHORTFEMALE_RED,
		SHORTFEMALE_WHITE,
		SHORTFEMALE_YELLOW,
		SHORTLAYERSFEMALE_BLUE,
		SHORTLAYERSFEMALE_BROWN,
		SHORTLAYERSFEMALE_GREEN,
		SHORTLAYERSFEMALE_GREY,
		SHORTLAYERSFEMALE_ORANGE,
		SHORTLAYERSFEMALE_PURPLE,
		SHORTLAYERSFEMALE_RED,
		SHORTLAYERSFEMALE_WHITE,
		SHORTLAYERSFEMALE_YELLOW,
		SHOULDERLENGHTFEMALE_BLUE,
		SHOULDERLENGHTFEMALE_BROWN,
		SHOULDERLENGHTFEMALE_GREEN,
		SHOULDERLENGHTFEMALE_GREY,
		SHOULDERLENGHTFEMALE_ORANGE,
		SHOULDERLENGHTFEMALE_PURPLE,
		SHOULDERLENGHTFEMALE_RED,
		SHOULDERLENGHTFEMALE_WHITE,
		SHOULDERLENGHTFEMALE_YELLOW,
		SIDEBURNSMALE_BLUE,
		SIDEBURNSMALE_BROWN,
		SIDEBURNSMALE_GREEN,
		SIDEBURNSMALE_GREY,
		SIDEBURNSMALE_ORANGE,
		SIDEBURNSMALE_PURPLE,
		SIDEBURNSMALE_RED,
		SIDEBURNSMALE_WHITE,
		SIDEBURNSMALE_YELLOW,
		SIDESWEPTFEMALE_BLUE,
		SIDESWEPTFEMALE_BROWN,
		SIDESWEPTFEMALE_GREEN,
		SIDESWEPTFEMALE_GREY,
		SIDESWEPTFEMALE_ORANGE,
		SIDESWEPTFEMALE_PURPLE,
		SIDESWEPTFEMALE_RED,
		SIDESWEPTFEMALE_WHITE,
		SIDESWEPTFEMALE_YELLOW,
		TRIMMEDMALE_BLUE,
		TRIMMEDMALE_BROWN,
		TRIMMEDMALE_GREEN,
		TRIMMEDMALE_GREY,
		TRIMMEDMALE_ORANGE,
		TRIMMEDMALE_PURPLE,
		TRIMMEDMALE_RED,
		TRIMMEDMALE_WHITE,
		TRIMMEDMALE_YELLOW,
		COLOUREDSTREAK_BLUE,
		COLOUREDSTREAK_GREEN,
		COLOUREDSTREAK_GREY,
		COLOUREDSTREAK_ORANGE,
		COLOUREDSTREAK_PURPLE,
		COLOUREDSTREAK_RED,
		COLOUREDSTREAK_WHITE,
		COLOUREDSTREAK_YELLOW,
		HAIRANDGLASSES_BLUE,
		HAIRANDGLASSES_BROWN,
		HAIRANDGLASSES_GREY,
		HAIRANDGLASSES_ORANGE,
		HAIRANDGLASSES_PURPLE,
		HAIRANDGLASSES_RED,
		HAIRANDGLASSES_YELLOW,
		HAIRANDHEADPHONES_BLUE,
		HAIRANDHEADPHONES_BROWN,
		HAIRANDHEADPHONES_GREY,
		HAIRANDHEADPHONES_ORANGE,
		HAIRANDHEADPHONES_PURPLE,
		HAIRANDHEADPHONES_RED,
		HAIRANDHEADPHONES_WHITE,
		HAIRANDHEADPHONES_YELLOW,
		CURLYFEMALE,
		COUNT
	}

	public enum Hat
	{
		NULL = -1,
		NONE,
		GUARD_01,
		ADMIRALHAT,
		BALACLAVA_BLACK,
		BALACLAVA_BLUE,
		BALACLAVA_GREEN,
		BALACLAVA_ORANGE,
		BALACLAVA_PURPLE,
		BALACLAVA_RED,
		BALACLAVA_WHITE,
		BALACLAVA_YELLOW,
		BASEBALLCAP_BLACK,
		BASEBALLCAP_BLUE,
		BASEBALLCAP_GREEN,
		BASEBALLCAP_ORANGE,
		BASEBALLCAP_PURPLE,
		BASEBALLCAP_RED,
		BASEBALLCAP_WHITE,
		BASEBALLCAP_YELLOW,
		BOBBLEHAT_BLACK,
		BOBBLEHAT_BLUE,
		BOBBLEHAT_GREEN,
		BOBBLEHAT_ORANGE,
		BOBBLEHAT_PURPLE,
		BOBBLEHAT_RED,
		BOBBLEHAT_WHITE,
		BOBBLEHAT_YELLOW,
		CHEFHAT,
		COWBOYHAT_BLACK,
		COWBOYHAT_BLUE,
		COWBOYHAT_BROWN,
		COWBOYHAT_GREEN,
		COWBOYHAT_ORANGE,
		COWBOYHAT_PURPLE,
		COWBOYHAT_RED,
		COWBOYHAT_WHITE,
		COWBOYHAT_YELLOW,
		FANCYUSHANKA_BLACK,
		FANCYUSHANKA_BLUE,
		FANCYUSHANKA_BROWN,
		FANCYUSHANKA_GREEN,
		FANCYUSHANKA_PURPLE,
		FANCYUSHANKA_YELLOW,
		FEDORA_BLACK,
		FEDORA_BLUE,
		FEDORA_GREEN,
		FEDORA_ORANGE,
		FEDORA_PURPLE,
		FEDORA_RED,
		FEDORA_WHITE,
		FEDORA_YELLOW,
		GUARD_02,
		HARDHAT,
		PILOTHAT,
		RIOTHELMET_01,
		SHERIFFHAT_BLUE,
		SHERIFFHAT_BROWN,
		SHERIFFHAT_GREEN,
		SHERIFFHAT_ORANGE,
		SHERIFFHAT_PURPLE,
		SHERIFFHAT_RED,
		SHERIFFHAT_WHITE,
		SHERIFFHAT_YELLOW,
		SPACEHELMET_BLACK,
		SPACEHELMET_BLUE,
		SPACEHELMET_ORANGE,
		SPACEHELMET_PURPLE,
		SPACEHELMET_WHITE,
		SPACEHELMET_YELLOW,
		SUPERSHERIFFHAT_BLUE,
		SUPERSHERIFFHAT_BROWN,
		SUPERSHERIFFHAT_GREEN,
		SUPERSHERIFFHAT_ORANGE,
		SUPERSHERIFFHAT_PURPLE,
		SUPERSHERIFFHAT_RED,
		SUPERSHERIFFHAT_WHITE,
		SUPERSHERIFFHAT_YELLOW,
		TOPHAT_BLACK,
		TOPHAT_BLUE,
		TOPHAT_GREEN,
		TOPHAT_ORANGE,
		TOPHAT_PURPLE,
		TOPHAT_RED,
		TOPHAT_WHITE,
		TOPHAT_YELLOW,
		TRAINDRIVERHAT,
		USHANKA_BLACK,
		USHANKA_BLUE,
		USHANKA_GREEN,
		USHANKA_ORANGE,
		USHANKA_PURPLE,
		USHANKA_RED,
		USHANKA_WHITE,
		USHANKA_YELLOW,
		HEADBAND_BLACK,
		HEADBAND_BLUE,
		HEADBAND_GREEN,
		HEADBAND_ORANGE,
		HEADBAND_PURPLE,
		HEADBAND_RED,
		HEADBAND_WHITE,
		HEADBAND_YELLOW,
		HIDDENVERSUS_WHITE,
		BEARSHANKA_BLUE,
		BEARSHANKA_BROWN,
		BEARSHANKA_GREEN,
		BEARSHANKA_GREY,
		BEARSHANKA_ORANGE,
		BEARSHANKA_PURPLE,
		BEARSHANKA_RED,
		BEARSHANKA_WHITE,
		BEARSHANKA_YELLOW,
		BUSHMANS_BLUE,
		BUSHMANS_GREEN,
		BUSHMANS_GREY,
		BUSHMANS_ORANGE,
		BUSHMANS_PURPLE,
		BUSHMANS_RED,
		BUSHMANS_WHITE,
		BUSHMANS_YELLOW,
		PUMPKINHAT,
		WITCH_BLACK,
		WITCH_BLUE,
		WITCH_GREEN,
		WITCH_ORANGE,
		WITCH_PURPLE,
		WITCH_RED,
		WITCH_WHITE,
		WITCH_YELLOW,
		CHEFHAT_HALLOWEEN,
		GRIMREAPER,
		GUARD_HALLOWEEN,
		MUMMYMASK,
		WEREWOLFMASK,
		WITCHESHAT,
		ANTLERS_01,
		ELF_01,
		SANTA_01,
		COCONUTHELMET,
		PARTYHAT,
		WHACKYTOPHAT,
		ARMORHELM_01,
		CROWN_01,
		MAIDENHAT_01,
		ROBINHOOD_01,
		MEDIEVALGUARDHELMET_01,
		GUARDELF_001,
		ELF_001,
		REWARDHAT,
		COUNT
	}

	public enum UpperFaceAccessory
	{
		NULL = -1,
		NONE,
		SUNGLASSES_BLACK,
		SUNGLASSES_BLUE,
		SUNGLASSES_GREEN,
		SUNGLASSES_ORANGE,
		SUNGLASSES_PURPLE,
		SUNGLASSES_RED,
		SUNGLASSES_WHITE,
		SUNGLASSES_YELLOW,
		ALIENMASK_BLUE,
		ALIENMASK_GREEN,
		ALIENMASK_PURPLE,
		ALIENMASK_RED,
		ALIENMASK_WHITE,
		ALIENMASK_YELLOW,
		GLASSES_BLACK,
		GLASSES_BLUE,
		GLASSES_GREEN,
		GLASSES_ORANGE,
		GLASSES_PURPLE,
		GLASSES_RED,
		GLASSES_WHITE,
		GLASSES_YELLOW,
		HOCKEYMASK_BLACK,
		HOCKEYMASK_BLUE,
		HOCKEYMASK_GREEN,
		HOCKEYMASK_ORANGE,
		HOCKEYMASK_PURPLE,
		HOCKEYMASK_RED,
		HOCKEYMASK_WHITE,
		HOCKEYMASK_YELLOW,
		ZORROMASK_BLACK,
		ZORROMASK_BLUE,
		ZORROMASK_GREEN,
		ZORROMASK_ORANGE,
		ZORROMASK_PURPLE,
		ZORROMASK_RED,
		ZORROMASK_WHITE,
		ZORROMASK_YELLOW,
		RIMLESSGLASSES,
		WOLFMASK,
		ZOMBIEMASK,
		COUNT
	}

	public enum LowerFaceAccessory
	{
		NULL = -1,
		NONE,
		MEDICMASK,
		BEARD_BLUE,
		BEARD_BROWN,
		BEARD_GREEN,
		BEARD_GREY,
		BEARD_ORANGE,
		BEARD_PURPLE,
		BEARD_RED,
		BEARD_WHITE,
		BEARD_YELLOW,
		GOATEE_BLUE,
		GOATEE_BROWN,
		GOATEE_GREEN,
		GOATEE_GREY,
		GOATEE_ORANGE,
		GOATEE_PURPLE,
		GOATEE_RED,
		GOATEE_WHITE,
		GOATEE_YELLOW,
		MOUTHBANDANA_BLACK,
		MOUTHBANDANA_BLUE,
		MOUTHBANDANA_GREEN,
		MOUTHBANDANA_ORANGE,
		MOUTHBANDANA_PURPLE,
		MOUTHBANDANA_RED,
		MOUTHBANDANA_WHITE,
		MOUTHBANDANA_YELLOW,
		MUSTACHE_BLUE,
		MUSTACHE_BROWN,
		MUSTACHE_GREEN,
		MUSTACHE_GREY,
		MUSTACHE_ORANGE,
		MUSTACHE_PURPLE,
		MUSTACHE_RED,
		MUSTACHE_WHITE,
		SCUBAMASK,
		GOATEE_BLACK,
		HALFGOATEE_BLUE,
		HALFGOATEE_BROWN,
		HALFGOATEE_GREEN,
		HALFGOATEE_GREY,
		HALFGOATEE_ORANGE,
		HALFGOATEE_PURPLE,
		HALFGOATEE_RED,
		HALFGOATEE_WHITE,
		HALFGOATEE_YELLOW,
		STUBBLE_BLUE,
		STUBBLE_GREEN,
		STUBBLE_ORANGE,
		STUBBLE_PURPLE,
		STUBBLE_RED,
		STUBBLE_WHITE,
		STUBBLE_YELLOW,
		MEDICMASK_HALLOWEEN,
		STRONGMANMUSTACHE_BLACK,
		STRONGMANMUSTACHE_BLUE,
		STRONGMANMUSTACHE_GREEN,
		STRONGMANMUSTACHE_GREY,
		STRONGMANMUSTACHE_ORANGE,
		STRONGMANMUSTACHE_PURPLE,
		STRONGMANMUSTACHE_RED,
		STRONGMANMUSTACHE_WHITE,
		STRONGMANMUSTACHE_YELLOW,
		GOATEE,
		FACEPAINT_001,
		FACEPAINT_002,
		FACEPAINT_003,
		FACEPAINT_004,
		COUNT
	}

	[Header("Data")]
	public List<BodyData> BodyTextureData = new List<BodyData>();

	public List<HairData> HairTextureData = new List<HairData>();

	public List<HatData> HatTextureData = new List<HatData>();

	public List<UpperFaceAccessoryData> AccessoryUpperFaceData = new List<UpperFaceAccessoryData>();

	public List<LowerFaceAccessoryData> AccessoryLowerFaceData = new List<LowerFaceAccessoryData>();

	private static CustomisationData m_Instance;

	public static CustomisationData GetInstance()
	{
		return m_Instance;
	}

	private void Awake()
	{
		m_Instance = this;
	}

	protected virtual void OnDestroy()
	{
		if (m_Instance == this)
		{
			m_Instance = null;
		}
	}

	public BodyData GetCustomisationData(BodyType body, SkinColour skin)
	{
		BodyData bodyData = null;
		for (int i = 0; i < BodyTextureData.Count; i++)
		{
			if (BodyTextureData[i].bodyType == body && BodyTextureData[i].skinColour == skin)
			{
				bodyData = BodyTextureData[i];
				break;
			}
		}
		if (bodyData == null)
		{
		}
		return bodyData;
	}

	public Material GetMaterialForOutfit(BodyType body, SkinColour skin, Outfit outfit)
	{
		BodyData customisationData = GetCustomisationData(body, skin);
		return customisationData.GetMaterialForOutfit(outfit);
	}

	public Material GetMaterialForHair(Hair hair)
	{
		Material result = null;
		if (hair >= Hair.NONE && (int)hair < HairTextureData.Count)
		{
			result = HairTextureData[(int)hair].material;
		}
		return result;
	}

	public Material GetMaterialForHat(Hat hat)
	{
		Material result = null;
		if (hat >= Hat.NONE && (int)hat < HatTextureData.Count)
		{
			result = HatTextureData[(int)hat].material;
		}
		return result;
	}

	public Material GetMaterialForUpperFace(UpperFaceAccessory accessory)
	{
		Material result = null;
		if (accessory >= UpperFaceAccessory.NONE && (int)accessory < AccessoryUpperFaceData.Count)
		{
			result = AccessoryUpperFaceData[(int)accessory].material;
		}
		return result;
	}

	public Material GetMaterialForLowerFace(LowerFaceAccessory accessory)
	{
		Material result = null;
		if (accessory >= LowerFaceAccessory.NONE && (int)accessory < AccessoryLowerFaceData.Count)
		{
			result = AccessoryLowerFaceData[(int)accessory].material;
		}
		return result;
	}
}
